export const WALKTHROUGH_COMPLETE = 'WALKTHROUGH_COMPLETE';
export const SET_FULL = 'SET_FULL';
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const SET_CURRENT_TOPIC = 'SET_CURRENT_TOPIC';
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ';
